const CAFEPRESS_EMAIL = "fdfdfsfdf";
const THREADLESS_USERNAME = "dsfsf";
const THREADLESS_PASSWORD = "fadsfdsf";
const CAFEPRESS_PASSWORD = "98reueoifjjfd";
module.exports = {
  CAFEPRESS_EMAIL,
  CAFEPRESS_PASSWORD,
  THREADLESS_USERNAME,
  THREADLESS_PASSWORD,
};
